### ISSUE TITLE
Hi, this is reall a nice Work in the uncertain decision making domain! 

### ISSUE THREAD

**Issue by Phd-Ma** [HKUST-Aerial-Robotics/eudm_planner#3]
I had succeed run  the EPSILON project according the read me on the line （https://github.com/HKUST-Aerial-Robotics/EPSILON）. 
**Well I Unable to integrate current decision-making project, error reported when I performed catkin_make!**
the running error shown as:

(1) catkin_ws/src/EPSILON/util/eudm_planner/inc/eudm_planner/eudm_planner.h:10:37: fatal error: common/basics/ma_filter.h:  There is no such file or directory
(2) catkin_ws/src/EPSILON/util/eudm_planner/inc/eudm_planner/eudm_itf.h: 

**#include "hkust_msg_transformer/Freespace.h"
#include "hkust_msg_transformer/LaneSet.h"
#include "hkust_msg_transformer/MotSet.h"
#include "hkust_msg_transformer/PlainOutput.h"
#include "hkust_msg_transformer/Vins.h"**

**error is the also same that There is no such file or directory**

I checked the relevant file directories and did not find the names of these header files

wonder if you could help me？ thanks a lot, best wish!

**Comment by MasterIzumi** [comment]
@Phd-Ma Thx for your comments.
I don't really understand the meaning of "Unable to integrate current decision-making project". Does that mean you are trying to build the eudm_planner individually? Actually, the behavior planning layer in the EPSILON is basically the same as eudm_planner. You can refer to the EPSILON repo for implementation details.

**Comment by Phd-Ma** [comment]
Thank you for your reply. I have successfully run the project. I will email you if I have any questions late！

发件人：Lu ZHANG ***@***.***>
发送日期：2021-12-13 17:13:59
收件人：HKUST-Aerial-Robotics/eudm_planner ***@***.***>
抄送人：Phd-Ma ***@***.***>,Mention ***@***.***>
主题：Re: [HKUST-Aerial-Robotics/eudm_planner] Hi, this is reall a nice Work in the uncertain decision making domain! (Issue #3)

@Phd-Ma Thx for your comments.
 I don't really understand the meaning of "Unable to integrate current decision-making project". Does that mean you are trying to build the eudm_planner individually? Actually, the behavior planning layer in the EPSILON is basically the same as eudm_planner. You can refer to the EPSILON repo for implementation details.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
